apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: tilt-avatar-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tilt-avatar-web
  template:
    metadata:
      labels:
        app: tilt-avatar-web
    spec:
      containers:
        - name: tilt-avatar-web
          #image: tilt-avatar-web
          image: registry.localhost:5000/tilt-avatar-web:latest
          env:
            - name: VITE_CLIENT_PORT
              value: '5735'
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: tilt-avatar-web
  namespace: default
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: tilt-avatar-web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tilt-avatar-ingress
  namespace: default
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - backend:
          service:
            name: tilt-avatar-web
            port:
              number: 3000
        path: /
        pathType: Exact
