apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: tilt-avatar-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tilt-avatar-web
  template:
    metadata:
      labels:
        app: tilt-avatar-web
    spec:
      containers:
        - name: tilt-avatar-web
          #image: tilt-avatar-web
          image: registry.localhost:5000/tilt-avatar-web:v1
          env:
            - name: VITE_CLIENT_PORT
              value: '5735'
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: tilt-avatar-svc
  namespace: default
spec:
  ports:
  - port: 5173
    protocol: TCP
    targetPort: 5173
  selector:
    app: tilt-avatar-web