version: '1.0'

on:
  push:
    branches:
      - main  # Or your default branch

env:
  BUILD: "v2"

services:
  docker:
    image: docker:dind
    privileged: true  # Required to run Docker in Docker

jobs:
  build:
    name: Build Web
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image (web)
        run: |
         docker build -t registry.localhost:5000/tilt-avatar-web:$BUILD -f ./deploy/web.dockerfile .
         
      - name: Push Docker Image to Local Registry
        run: |
          docker push registry.localhost:5000/tilt-avatar-web:$BUILD

      #- name: Build Docker Image (api) 
      #  run: |
      #   docker build -t registry.localhost:5000/tilt-avatar-api:$BUILD -f ./deploy/api.dockerfile .  

      #- name: Push Docker Image to Local Registry
      #  run: |
      #    docker push registry.localhost:5000/tilt-avatar-api:$BUILD

      #- name: Echo what was done
      #  shell: bash
      #  run: |
      #    echo "web: registry.localhost:5000/tilt-avatar-web:$BUILD"
      #    echo "api: registry.localhost:5000/tilt-avatar-api:$BUILD"           



       
 

     
        